export interface eventInterface {
    eventId: number,
    eventImage: string,
    eventName: string,
    eventInfo: string,
    eventSellStartTimestamp: string,
    eventSellEndTimestamp: string,
    eventStartTimestamp: string,
    eventEndTimestamp: string,
    eventIsstate: boolean,
    eventTypeId: number,
    eventTypeName: string,
    eventLocationId: number,
    eventLocationName: string,
    eventLocationImage: string,
    eventLocationInfo: string,
    eventLocationAddress: string,
    companyId: number,
    companyName: string,
}